FROM debian:stretch-slim

#RUN apk add --no-cache curl bash
RUN apt-get update && apt-get install -y curl

ARG http_port=9999
ARG testerum_version
ARG testerum_download_url=https://testerum.com/download/testerum-linux-${testerum_version}.tar.gz

ENV TESTERUM_HOME /var/testerum_home

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r testerum && useradd -r -g testerum testerum

WORKDIR /usr/share

RUN curl -fsSL ${testerum_download_url} -o testerum.tar.gz \
    && mkdir -p testerum \
    && tar -xzf testerum.tar.gz -C testerum \
    && rm testerum.tar.gz;

# for main web interface:
EXPOSE ${http_port}

WORKDIR /usr/share/testerum

ENTRYPOINT ["./start.sh"]
